name: Run All Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install test dependencies
        if [ -f backend/tests/requirements.txt ]; then pip install -r backend/tests/requirements.txt; fi
        # Install production dependencies
        if [ -f saddleup/requirements.txt ]; then pip install -r saddleup/requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
    - name: Install Node.js dependencies
      run: |
        # Check for different possible frontend locations
        if [ -d "frontend" ]; then
          echo "Found frontend directory"
          cd frontend && npm install
        elif [ -d "saddleup/frontend" ]; then
          echo "Found saddleup/frontend directory"
          cd saddleup/frontend && npm install
        elif [ -f "package.json" ]; then
          echo "Found package.json in root"
          npm install
        else
          echo "No Node.js project found, skipping npm install"
        fi
        
    - name: Find all test files
      run: |
        echo "Finding all Python test files..."
        find . -name "*_test.py" -type f | head -20
        echo "Finding all JavaScript test files..."
        find . -name "*_test.js" -o -name "*.test.js" -o -name "*_test.ts" -o -name "*.test.ts" | head -20
        
    - name: Run Python tests
      run: |
        if [ -f "test_runner.py" ]; then
          echo "Running Python test runner..."
          python test_runner.py
        else
          echo "No test_runner.py found, checking for individual Python tests..."
          if find . -name "*_test.py" -type f | grep -q .; then
            echo "Running individual Python tests with pytest..."
            python -m pytest $(find . -name "*_test.py") -v
          else
            echo "No Python tests found, skipping Python test execution"
          fi
        fi
        
    - name: Run Node.js tests
      run: |
        # Run Node.js tests based on project structure
        if [ -d "frontend" ]; then
          echo "Running frontend tests..."
          cd frontend && npm test
        elif [ -d "saddleup/frontend" ]; then
          echo "Running saddleup/frontend tests..."
          cd saddleup/frontend && npm test
        elif [ -f "package.json" ]; then
          echo "Running root Node.js tests..."
          npm test
        else
          echo "No Node.js tests found, skipping"
        fi
        
    - name: Generate test summary
      run: |
        echo "All tests completed successfully!"
        find . -name "*_test.py" -type f | wc -l | xargs echo "Python test files found:"
        find . -name "*_test.js" -o -name "*.test.js" -o -name "*_test.ts" -o -name "*.test.ts" | wc -l | xargs echo "JavaScript test files found:"