name: Run All Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install test dependencies
        if [ -f backend/tests/requirements.txt ]; then pip install -r backend/tests/requirements.txt; fi
        # Install production dependencies
        if [ -f saddleup/requirements.txt ]; then pip install -r saddleup/requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
    # - name: Run backend tests
    #   run: |
    #     echo "Running backend tests using test_runner..."
    #     cd saddleup/backend
    #     python tests/test_runner.py
        
    # - name: Run backend tests with coverage
    #   run: |
    #     echo "Running backend tests with coverage..."
    #     cd saddleup/backend
    #     python -m pytest tests/ --cov=. --cov-report=html --cov-report=term-missing --cov-fail-under=80

    # - name: Install linting tools
    #   run: pip install flake8 black

    # - name: Run linting
    #   run: |
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     black --check .

    - name: Setup Node.js for frontend tests
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install frontend dependencies
      run: |
        cd saddleup/frontend
        npm install
        
    - name: Run frontend tests
      run: |
        echo "Running frontend tests..."
        cd saddleup/frontend
        npm test
        
    - name: Run frontend tests with coverage
      run: |
        echo "Running frontend tests with coverage..."
        cd saddleup/frontend
        npm run test:coverage